config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get 'greeter/hello'
  get 'greeter/goodbye' => 'greeter#goodbye'
  get 'books/images' => 'books#images'
  get 'books/index'

  root 'books#index'
  resources :entries, defaults: { format: 'json' }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
# frozen_string_literal: true

require 'httparty'

class Book
  include HTTParty

  base_uri 'https://www.googleapis.com/books/v1/volumes'

  format :json

  def self.about(term)
    cleaned_up_term = term.gsub /\s+/, '+'
    get('', query: { q: "intitle:#{cleaned_up_term}", maxResults: '4', printType: 'books' })['items'] || []
  end

  def self.image
    response = get('', query: { q: "intitle:'Star+Wars'", maxResults: '4', printType: 'books' })['items'] || []
    images = []
    response.each do |x|
      images << x['volumeInfo']['imageLinks']['thumbnail']
    end
    images
  end

  def self.magic_the_gathering(name)
    cleaned_up_name = name.gsub /\s+/, ' '
    response = get('https://api.magicthegathering.io/v1/cards', query: { name: cleaned_up_name.to_s })['cards'] || []
    images = []
    response.each do |card|
      images << card['imageUrl']
    end
    images
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/books_controller.rb
# frozen_string_literal: true

class BooksController < ApplicationController
  def index
    # If params[:looking_for] exists use that, otherwise 'Djinn'
    @search_term = params[:looking_for] || 'Djinn'
    @books = Book.about(@search_term)
    @images = Book.image
    @magic_images = Book.magic_the_gathering(@search_term)
  end
  # def images
  #   @magic_images = Book.magic_the_gathering "Djinn"
  # end
  def map_isbn(books)
    # TODO - 
  end
  def sort_books(books) 
    # TODO - sort the books
  end
end

app/controllers/greeter_controller.rb
class GreeterController < ApplicationController
  def hello
    random_names = ["Susan", "Cathy", "Jimmy", "Dave", "Tiffany"]
    @name = random_names.sample
    @time = Time.now
    @times_visited ||= 0
    @times_visited += 1
  end
  def goodbye
    random_names = ["Susan", "Cathy", "Jimmy", "Dave", "Tiffany"]
    @name = random_names.sample
    @time = Time.now
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/greeter_helper.rb
module GreeterHelper
    def formatted_time(time) 
        time.strftime("%l:%M%P")
    end
end

app/views/books/images.html.erb
<% if @magic_images.empty? %>

No cards found matching that criteria

<% else %>

<table border=1>
    <tr>
        <th></th>
    </tr>
    <% @magic_images.each do |image| %>
    <tr>
        <td> <%= image_tag(image) %></td>
    </tr>
    <% end %>
</table>

<% end %>

app/views/books/index.html.erb
<h1>Books#index</h1>
<p>Find me in app/views/books/index.html.erb</p>

<div id='search-form'>
  <%= form_tag(root_path, method: :get) do %>
    <%= search_field_tag :looking_for, nil, placeholder: "Book Title..." %>
    <%= submit_tag 'Search', id: 'submit-button' %>
  <% end %>
</div>

<% if @books.empty? %>

No books found matching '<%= @search_term %>'

<% else %>

<table border="1">
    <tr>
        <th></th>
        <th>Title</th>
        <th>Author</th>
        <th>Description</th>
    </tr>
    <% @books.each do |book| %>
    <tr class=<%= cycle('even', 'odd')%>>
        <td> <%= link_to image_tag(book["volumeInfo"]["imageLinks"]["thumbnail"]),
             book["volumeInfo"]["previewLink"] if book["volumeInfo"]["imageLinks"]%></td>
        <td> <%= book["volumeInfo"]["title"] if book["volumeInfo"]["title"]%></td>
        <td> <%= book["volumeInfo"]["authors"].join(',') if book["volumeInfo"]["authors"]%></td>
        <td> <%= sanitize(book["volumeInfo"]["description"])%></td>
    </tr>
    <% end %>
</table>

<% end %>

app/views/greeter/goodbye.html.erb
<h1>Goodbye, <%= @name %></h1>
<p>.......The time now is <%= formatted_time @time %></p>
<p> <%= link_to "Hello", greeter_hello_path %></p>

app/views/greeter/hello.html.erb
<h1>Greeter#hello</h1>
<p>Find me in app/views/greeter/hello.html.erb</p>
<p> <%= link_to "Goodbye", greeter_goodbye_path %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FirstApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>